### ISSUE TITLE
Le classifiche non sono corrette

### ISSUE THREAD

**Issue by mrsingh-10** [caldi99/Database2-Project#1]
[QueryWinner2016.txt](https://github.com/caldi99/Database2-Project/files/9995061/QueryWinner2016.txt)

Secondo la nostra query risulterebbe Warriors ma in realtà è [Cleveland Cavaliers](https://www.google.com/search?rlz=1C1ONGR_itIT1030IT1030&q=Cleveland+Cavaliers&stick=H4sIAAAAAAAAAONgVuLQz9U3yMo1z3vEaMwt8PLHPWEprUlrTl5jVOHiCs7IL3fNK8ksqRQS42KDsnikuLjgmngWsQo756SWpeYk5qUoOCeWJeZkphYVAwABzLdNWAAAAA&sa=X&ved=2ahUKEwjAkIrj36j7AhUBRPEDHWUVBqcQzIcDKAB6BAgUEAE)

**Comment by caldi99** [comment]
Si, ma noi contiamo chi ha vinto più partite non chi è campione..
